name: Build window release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.7.3"
          cache: true
      - name: Enable window support
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build runner for Hive database
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build exe for windows
        run: flutter build windows --release

      - name: Archive built result
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: Localization-Generator-windows-${{inputs.version}}.zip
          directory: build/windows/runner/Release

      - name: "Upload to Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: Localization-Generator-windows-${{inputs.version}}
          path: build/windows/runner/Release/Localization-Generator-windows-${{inputs.version}}.zip
          retention-days: 2
